from scrapy.item import Item, Field

class GameItem(Item):
    url = Field()
    Id = Field()
    date = Field()
    home_name = Field()
    visit_name = Field()
    date = Field()
    home_FGM = Field()
    home_FGA = Field()
    home_3PM = Field()
    home_3PA = Field()
    home_FTM = Field()
    home_FTA = Field()
    home_OREB = Field()
    home_AST = Field()
    home_STL = Field()
    home_BLK = Field()
    home_TO = Field()
    home_PF = Field()
    home_PTS = Field()
    visit_FGM = Field()
    visit_FGA = Field()
    visit_3PM = Field()
    visit_3PA = Field()
    visit_FTM = Field()
    visit_FTA = Field()
    visit_OREB = Field()
    visit_AST = Field()
    visit_STL = Field()
    visit_BLK = Field()
    visit_TO = Field()
    visit_PF = Field()
    visit_PTS = Field()

